/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Classes_KargoBilgi.Temel1;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author theincas
 */
public class KargoBilgiForm extends javax.swing.JFrame {

    /**
     * Creates new form KargoBilgiForm
     */
    public KargoBilgiForm() {
        initComponents();
        kListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_KargoBilgi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_Home = new javax.swing.JButton();
        btn_Ekle = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        Btn_Sil = new javax.swing.JButton();
        Btn_Ara = new javax.swing.JButton();
        btn_Temizle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBox_KargoNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBox_KargoHacim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBox_KargoUcret = new javax.swing.JTextField();
        txtBox_KargoDurum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_GonderiTarih = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtBox_MusteriNo = new javax.swing.JTextField();
        txtBox_PersonelNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBox_GonderilenAdres = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_KargoBilgi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_KargoBilgi);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(247, 730));

        btn_Home.setBackground(new java.awt.Color(102, 0, 102));
        btn_Home.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_Home.setText("ANASAYFA");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        btn_Ekle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Ekle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Ekle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add2.png"))); // NOI18N
        btn_Ekle.setText("Ekle");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Guncelle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Guncelle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Guncelle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        Btn_Sil.setBackground(new java.awt.Color(102, 0, 102));
        Btn_Sil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Btn_Sil.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete2.png"))); // NOI18N
        Btn_Sil.setText("Sil");
        Btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SilActionPerformed(evt);
            }
        });

        Btn_Ara.setBackground(new java.awt.Color(102, 0, 102));
        Btn_Ara.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Btn_Ara.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        Btn_Ara.setText("Ara");
        Btn_Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AraActionPerformed(evt);
            }
        });

        btn_Temizle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Temizle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Temizle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Temizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_Temizle.setText("Temizle");
        btn_Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
            .addComponent(btn_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Temizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(132, 0, 140));
        jPanel2.setPreferredSize(new java.awt.Dimension(1032, 205));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kargo Numarası");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kargo Hacmi");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kargo Ücreti");

        txtBox_KargoDurum.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kargo Durumu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Musteri Numarası");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Personel Numarası");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gönderilen Tarih");

        jDateChooser_GonderiTarih.setDateFormatString("yyyy-MM-dd");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gönderilen Adres");

        txtBox_GonderilenAdres.setColumns(20);
        txtBox_GonderilenAdres.setRows(5);
        jScrollPane2.setViewportView(txtBox_GonderilenAdres);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBox_KargoNo)
                            .addComponent(txtBox_KargoHacim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtBox_KargoDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtBox_KargoUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBox_PersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBox_MusteriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(jDateChooser_GonderiTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBox_MusteriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBox_PersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_GonderiTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(txtBox_KargoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBox_KargoHacim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBox_KargoUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                            .addComponent(txtBox_KargoDurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void kListele()
    {
        DefaultTableModel table=new DefaultTableModel();
        Temel1 t=new Temel1();
        table.addColumn("kargoNo");
        table.addColumn("kargoHacim");
        table.addColumn("kargoUcret");
        table.addColumn("kargoDurum");
        table.addColumn("gonderiTarih");
        table.addColumn("gonderiAdres");
        table.addColumn("musteriNoFk");
        table.addColumn("personelNoFk");
        ResultSet rs;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection baglanti=null;
            baglanti=DriverManager.getConnection("jdbc:mysql://localhost:3306/DbKargoTakip","root","");
            String query =("Select * from tbl_kargobilgileri");
            //PreparedStatement pstm = baglanti.prepareStatement(query);
            //rs=pstm.executeQuery();
            
            //pstm.execute();
             Statement S=baglanti.createStatement();
             ResultSet R=S.executeQuery(query);
             while(R.next())
             {
                 table.addRow(new Object[]{
                    R.getInt(1),
                    R.getInt(2),
                    R.getInt(3),
                    R.getString(4),
                    R.getString(5),
                    R.getString(6),
                    R.getInt(7),
                    R.getInt(8)
                 });
             }
             jTable_KargoBilgi.setModel(table);
            
            baglanti.close();
        } catch (Exception e) {
            System.out.println("Listeleme Basarisiz oldu");
        }
    }
    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        Temel1 t=new Temel1();
        try {
            t.setKargoNo(Integer.parseInt(txtBox_KargoNo.getText()));
            t.setKargoHacim(Integer.parseInt(txtBox_KargoHacim.getText()));
            t.setKargoUcret(Integer.parseInt(txtBox_KargoUcret.getText()));
            t.setKargoDurum(txtBox_KargoDurum.getText());
            t.setGonderiTarih(((JTextField)jDateChooser_GonderiTarih.getDateEditor().getUiComponent()).getText());
            t.setGonderiAdres(txtBox_GonderilenAdres.getText());
            t.setMusteriNum(Integer.parseInt(txtBox_MusteriNo.getText()));
            t.setPersonelNum(Integer.parseInt(txtBox_PersonelNo.getText()));
            t.kEkle();
            kListele();
            } catch (Exception e) {
                System.out.println("Ekleme Hatası");
            }
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void Btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SilActionPerformed
        Temel1 t=new Temel1();

        try {
             t.setKargoNo(Integer.parseInt(txtBox_KargoNo.getText()));

            t.kSil();
//            txtBox_KargoHacim.setText(t.getKargoHacim());
//            txtBox_KargoUcret.setText(t.getKargoUcret());
//            txtBox_KargoDurum.setText(t.getKargoDurum());
//            jDateChooser_GonderiTarih.setDateFormatString(t.getGonderiTarih());
//            txtBox_GonderilenAdres.setText(t.getGonderiAdres());
//            txtBox_MusteriNo.setText(t.getPersonelAdres());
//            txtBox_PersonelNo.setText(t.getPersonelEposta());
            kListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_Btn_SilActionPerformed

    private void Btn_AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AraActionPerformed
        Temel1 t=new Temel1();

        try {
            t.setKargoNo(Integer.parseInt(txtBox_KargoNo.getText()));
            t.kAra();
            txtBox_KargoHacim.setText(String.valueOf(t.getKargoHacim()));
            txtBox_KargoUcret.setText(String.valueOf(t.getKargoUcret()));
            txtBox_KargoDurum.setText(t.getKargoDurum());
            ((JTextField)jDateChooser_GonderiTarih.getDateEditor().getUiComponent()).setText(t.getGonderiTarih());
            txtBox_GonderilenAdres.setText(t.getGonderiAdres());
            txtBox_MusteriNo.setText(String.valueOf(t.getMusteriNum()));
            txtBox_PersonelNo.setText(String.valueOf(t.getPersonelNum()));
            kListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_Btn_AraActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        Temel1 t=new Temel1();

        try {
            t.setKargoNo(Integer.parseInt(txtBox_KargoNo.getText()));
            t.setKargoHacim(Integer.parseInt(txtBox_KargoHacim.getText()));
            t.setKargoUcret(Integer.parseInt(txtBox_KargoUcret.getText()));
            t.setKargoDurum(txtBox_KargoDurum.getText());
            t.setGonderiTarih(((JTextField)jDateChooser_GonderiTarih.getDateEditor().getUiComponent()).getText());
            t.setGonderiAdres(txtBox_GonderilenAdres.getText());
            t.setMusteriNum(Integer.parseInt(txtBox_MusteriNo.getText()));
            t.setPersonelNum(Integer.parseInt(txtBox_PersonelNo.getText()));
            t.kGuncelle();
            kListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        Anasayfa aForm=new Anasayfa();
        aForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TemizleActionPerformed
        txtBox_GonderilenAdres.setText("");
        txtBox_KargoDurum.setText("");
        txtBox_KargoHacim.setText("");
        txtBox_KargoNo.setText("");
        txtBox_KargoUcret.setText("");
        txtBox_MusteriNo.setText("");
        txtBox_PersonelNo.setText("");
        jDateChooser_GonderiTarih.setCalendar(null);
    }//GEN-LAST:event_btn_TemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoBilgiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoBilgiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoBilgiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoBilgiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoBilgiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ara;
    private javax.swing.JButton Btn_Sil;
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Temizle;
    private com.toedter.calendar.JDateChooser jDateChooser_GonderiTarih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_KargoBilgi;
    private javax.swing.JTextArea txtBox_GonderilenAdres;
    private javax.swing.JTextField txtBox_KargoDurum;
    private javax.swing.JTextField txtBox_KargoHacim;
    private javax.swing.JTextField txtBox_KargoNo;
    private javax.swing.JTextField txtBox_KargoUcret;
    private javax.swing.JTextField txtBox_MusteriNo;
    private javax.swing.JTextField txtBox_PersonelNo;
    // End of variables declaration//GEN-END:variables
}
