
import Classes_Personel.Temel1;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theincas
 */
public class PersonelForm extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public PersonelForm() {
        initComponents();
        pListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Personel = new javax.swing.JTable();
        sidePane = new javax.swing.JPanel();
        btn_Anasayfa = new javax.swing.JButton();
        btn_Ekle = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        Btn_Sil = new javax.swing.JButton();
        Btn_Ara = new javax.swing.JButton();
        btn_Temizle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBox_PersonelAd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBox_PersonelNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBox_PersonelSoyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBox_PersonelTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBox_PersonelAdres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBox_PersonelEposta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Personel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Personel);

        sidePane.setBackground(new java.awt.Color(102, 0, 102));

        btn_Anasayfa.setBackground(new java.awt.Color(102, 0, 102));
        btn_Anasayfa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Anasayfa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Anasayfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_Anasayfa.setText("ANASAYFA");
        btn_Anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnasayfaActionPerformed(evt);
            }
        });

        btn_Ekle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Ekle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Ekle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_Ekle.setText("Ekle");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Guncelle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Guncelle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Guncelle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        Btn_Sil.setBackground(new java.awt.Color(102, 0, 102));
        Btn_Sil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Btn_Sil.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        Btn_Sil.setText("Sil");
        Btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SilActionPerformed(evt);
            }
        });

        Btn_Ara.setBackground(new java.awt.Color(102, 0, 102));
        Btn_Ara.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Btn_Ara.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        Btn_Ara.setText("Ara");
        Btn_Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AraActionPerformed(evt);
            }
        });

        btn_Temizle.setBackground(new java.awt.Color(102, 0, 102));
        btn_Temizle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Temizle.setForeground(new java.awt.Color(255, 255, 255));
        btn_Temizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_Temizle.setText("Temizle");
        btn_Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePaneLayout = new javax.swing.GroupLayout(sidePane);
        sidePane.setLayout(sidePaneLayout);
        sidePaneLayout.setHorizontalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
            .addComponent(btn_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Temizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePaneLayout.setVerticalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btn_Anasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(132, 0, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personel Adı");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personel Numarası");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Personel Soyadı");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Personel Telefon");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Personel Adres");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Personel E-Posta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBox_PersonelSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtBox_PersonelNo)
                    .addComponent(txtBox_PersonelAd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBox_PersonelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBox_PersonelAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBox_PersonelEposta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBox_PersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtBox_PersonelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBox_PersonelAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBox_PersonelAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBox_PersonelSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtBox_PersonelEposta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void pListele()
    {
        DefaultTableModel table=new DefaultTableModel();
        Temel1 t=new Temel1();
        table.addColumn("personelNo");
        table.addColumn("personelAdi");
        table.addColumn("personelSoyadi");
        table.addColumn("personelTel");
        table.addColumn("personelAdres");
        table.addColumn("personelEposta");
        ResultSet rs;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection baglanti=null;
            baglanti=DriverManager.getConnection("jdbc:mysql://localhost:3306/DbKargoTakip","root","");
            String query =("Select * from tbl_personel");
            //PreparedStatement pstm = baglanti.prepareStatement(query);
            //rs=pstm.executeQuery();
            
            //pstm.execute();
             Statement S=baglanti.createStatement();
             ResultSet R=S.executeQuery(query);
             while(R.next())
             {
                 table.addRow(new Object[]{
                    R.getInt(1),
                    R.getString(2),
                    R.getString(3),
                    R.getString(4),
                    R.getString(5),
                    R.getString(6)
                 });
             }
             jTable_Personel.setModel(table);
            
            baglanti.close();
        } catch (Exception e) {
            System.out.println("Listeleme Basarisiz oldu");
        }
         
    }
    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        Temel1 t=new Temel1();
        
        try {
            t.setPersonelNo(Integer.parseInt(txtBox_PersonelNo.getText()));
            t.setPersonelAd(txtBox_PersonelAd.getText());
            t.setPersonelSoyad(txtBox_PersonelSoyad.getText());
            t.setPersonelTel(txtBox_PersonelTel.getText());
            t.setPersonelAdres(txtBox_PersonelAdres.getText());
            t.setPersonelEposta(txtBox_PersonelEposta.getText());
            t.pEkle();
            pListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
       
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        Temel1 t=new Temel1();
        
        try {
            t.setPersonelNo(Integer.parseInt(txtBox_PersonelNo.getText()));
            t.setPersonelAd(txtBox_PersonelAd.getText());
            t.setPersonelSoyad(txtBox_PersonelSoyad.getText());
            t.setPersonelTel(txtBox_PersonelTel.getText());
            t.setPersonelAdres(txtBox_PersonelAdres.getText());
            t.setPersonelEposta(txtBox_PersonelEposta.getText());
            t.pGuncelle();
            pListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void Btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SilActionPerformed
        Temel1 t=new Temel1();
        
        try {
            t.setPersonelNo(Integer.parseInt(txtBox_PersonelNo.getText()));

            
            t.pSil();
            txtBox_PersonelAd.setText(t.getPersonelAd());
            txtBox_PersonelSoyad.setText(t.getPersonelSoyad());
            txtBox_PersonelTel.setText(t.getPersonelTel());
            txtBox_PersonelAdres.setText(t.getPersonelAdres());
            txtBox_PersonelEposta.setText(t.getPersonelEposta());
            pListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_Btn_SilActionPerformed

    private void Btn_AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AraActionPerformed
        Temel1 t=new Temel1();
        
        try {
            t.setPersonelNo(Integer.parseInt(txtBox_PersonelNo.getText()));
//            t.setMusteriAd(txtBox_Adi.getText());
//            t.setMusteriSoyad(txtBox_Soyadi.getText());
//            t.setMusteriTel(txtBox_Tel.getText());
//            t.setMusteriAdres(txtBox_Adres.getText());
//            t.setMusteriEposta(txtBox_Eposta.getText());
            
            t.pAra();
            txtBox_PersonelAd.setText(t.getPersonelAd());
            txtBox_PersonelSoyad.setText(t.getPersonelSoyad());
            txtBox_PersonelTel.setText(t.getPersonelTel());
            txtBox_PersonelAdres.setText(t.getPersonelAdres());
            txtBox_PersonelEposta.setText(t.getPersonelEposta());
            pListele();
        } catch (Exception e) {
            System.out.println("Hata");
        }
    }//GEN-LAST:event_Btn_AraActionPerformed

    private void btn_AnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnasayfaActionPerformed
        Anasayfa aForm=new Anasayfa();
        aForm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_AnasayfaActionPerformed

    private void btn_TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TemizleActionPerformed
        txtBox_PersonelAd.setText("");
        txtBox_PersonelAdres.setText("");
        txtBox_PersonelEposta.setText("");
        txtBox_PersonelNo.setText("");
        txtBox_PersonelSoyad.setText("");
        txtBox_PersonelTel.setText("");
        
    }//GEN-LAST:event_btn_TemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ara;
    private javax.swing.JButton Btn_Sil;
    private javax.swing.JButton btn_Anasayfa;
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Personel;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTextField txtBox_PersonelAd;
    private javax.swing.JTextField txtBox_PersonelAdres;
    private javax.swing.JTextField txtBox_PersonelEposta;
    private javax.swing.JTextField txtBox_PersonelNo;
    private javax.swing.JTextField txtBox_PersonelSoyad;
    private javax.swing.JTextField txtBox_PersonelTel;
    // End of variables declaration//GEN-END:variables
}
